site_name: Idev
site_url: https://hacktives.github.io/Hacktives/
repo_url: https://github.com/Hacktives/hacktives.github.io/Hacktives/
repo_name: Hacktives

nav:
  - Home: index.md
  - 'about.md'

theme:
  palette: 
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
      text: Roboto
  features:
    - toc.integrate
  name: material
  custom_dir: docs/overrides

  shortcuts:
      help: 191    # ?
      next: 78     # n
      previous: 80 # p
      search: 83   # s readthedocs

markdown_extensions:
    - toc:
        permalink: "#"
plugins:
- search

extra:
  analytics:
    provider: google
    property: G-0F3FK713C2
